[fix] Working release

diff --git a/.github/workflows/release_epitech.yml b/.github/workflows/release_epitech.yml
--- a/.github/workflows/release_epitech.yml
+++ b/.github/workflows/release_epitech.yml
@@ -7,7 +7,7 @@ on:
 env:
   PROJECT_FOLDER: test
   RELEASE_NAME: interpretor
-  BINARY_NAME: my-lisp-interpretor-exe
+  BINARY_NAME: my-lisp-interpreter-exe
 
 jobs:
   get_date:
@@ -27,7 +27,9 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Build binary
-        run: make re
+        run: |
+          make re
+          if [ -x ${{ env.BINARY_NAME }} ]; then echo "Binary was built succesfully."; else echo "${{ env.BINARY_NAME }} was not found..." && exit 84 ; fi
     
       - name: Create Release
         id: create_release
@@ -50,7 +52,7 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
-          asset_path: ${{ env.BINARY_NAME }}
+          asset_path: "./${{ env.BINARY_NAME }}"
           asset_name: ${{ env.BINARY_NAME }}
           asset_content_type: application/exe
 
